---
- name: Install Python3
  hosts: ubuntu
  gather_facts: false
  become: yes
  roles:
   - install_python3

- name: Install required system packages, add GPG key and Docker repository
  hosts: ubuntu
  become: yes
  roles:
   - install_dependencies
 
- name: Install Docker, Docker-compose and start Docker daemon
  hosts: ubuntu
  become: yes
  roles:
   - install_and_start_docker


- name: Add user to the docker group
  hosts: ubuntu
  become: yes
  roles:
   - create_user

- name: Start docker container
  hosts: ubuntu
  vars_prompt:
   - name: docker_username
     prompt: Enter username for private docker registry
   - name: docker_password
     prompt: Enter password for private docker registry
  roles:
   - start_container
