- name: Copy docker-compose.yaml file
  copy:
    src: docker-compose.yaml
    dest: /home/sergei/docker-compose.yaml
- name: Docker login
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ docker_username }}"
    password: "{{ docker_pasword }}"
- name: Start container from docker-compose
  docker_compose:
    project_src: /home/sergei/docker-compose.yaml
    state: present

