- name: Update apt packages
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
- name: Install Docker
  apt:
    name: docker-ce
    state: present
- name: Install Docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{ lookup('pipe', 'uname -m') }}
    dest: /usr/local/bin/docker-compose
    mode: +x
- name: Start docker daemon
  service:
    name: docker
    state: started
    enabled: yes
- name: Install docker and python module
  pip:
    name:
      - docker
      - requests
      - docker-compose

